[build]
  command = "npx prisma generate --no-engine && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[crons]]
  schedule = "*/5 * * * *"
  path = "/api/sync?secret=praise2234&mode=live"

[[crons]]
  schedule = "0 * * * *"
  path = "/api/sync?secret=praise2234&mode=daily"

[[crons]]
  schedule = "0 0 * * *"
  path = "/api/sync?secret=praise2234&mode=daily"