import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Notice — MatchInsense" };

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: "100vh", paddingTop: "56px", background: "var(--bg)" }}>

      <div style={{ borderBottom: "1px solid var(--border)", background: "var(--bg-1)", padding: "40px 20px 32px" }}>
        <div style={{ maxWidth: 720, margin: "0 auto" }}>
          <p style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: "0.18em", color: "var(--text-3)", textTransform: "uppercase", marginBottom: 10 }}>Legal</p>
          <h1 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(28px, 5vw, 42px)", fontWeight: 800, color: "var(--text)", margin: "0 0 12px" }}>Privacy Notice</h1>
          <p style={{ fontSize: 12, color: "var(--text-3)", margin: 0, fontFamily: "var(--font-mono)" }}>Last updated: March 2026</p>
        </div>
      </div>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "40px 20px 80px", display: "flex", flexDirection: "column", gap: 32 }}>

        {/* Key fact box */}
        <div style={{ background: "var(--bg-card)", border: "1px solid var(--accent-mid)", borderRadius: "var(--r-xl)", padding: "18px 20px" }}>
          <p style={{ fontSize: 13, fontWeight: 700, color: "var(--accent)", margin: "0 0 6px" }}>The short version</p>
          <p style={{ fontSize: 13, color: "var(--text-2)", lineHeight: 1.75, margin: 0 }}>
            MatchInsense requires <strong style={{ color: "var(--text)" }}>no account, no login, no sign-up</strong>. We collect no personal data from users. AI reports are stored only on your own device and never sent to us.
          </p>
        </div>

        {[
          {
            title: "1. Who We Are",
            body: `MatchInsense is a free, publicly accessible live football intelligence platform. We are committed to your privacy. Since we require no registration, we have designed the platform to operate with zero personal data collection.

Contact: privacy@matchinsense.com`
          },
          {
            title: "2. Data We Do Not Collect",
            body: `Because MatchInsense has no accounts, we do not collect:
• Names, email addresses or passwords
• Payment or financial information
• Device identifiers tied to individuals
• Location data
• Behavioural tracking or advertising profiles

We do not use Google Analytics, Facebook Pixel or any third-party analytics or advertising trackers.`
          },
          {
            title: "3. Data Automatically Generated",
            body: `Standard web server logs (IP address, browser type, pages visited, timestamps) are automatically generated by our hosting provider Vercel when you access the platform. These logs are used solely for security monitoring and are retained for a maximum of 30 days. They are not used to identify, profile or track individuals.`
          },
          {
            title: "4. Your Browser Storage (localStorage)",
            body: `AI reports you generate (Match Reports, Previews, Betting Insights) are saved in your browser's localStorage on your device only. This data:
• Never leaves your device
• Is never transmitted to our servers
• Can be deleted at any time via the AI Reports page ("Clear all") or your browser settings`
          },
          {
            title: "5. Third-Party Services",
            body: `We use the following services to operate MatchInsense. None receive personal data about you:

• api-sports.io — live football data provider (match scores, lineups, standings)
• Groq AI — generates AI match reports from match statistics only (no personal data transmitted)
• Vercel — hosting platform (manages standard server logs under their own privacy policy)
• Supabase — database used to store football fixture data only (no personal user data stored)

These services operate under their own privacy policies.`
          },
          {
            title: "6. Cookies",
            body: `We use no advertising cookies, tracking cookies or third-party analytics cookies.

The only browser storage we use is localStorage (described in section 4). We do not set any cookies.`
          },
          {
            title: "7. Children's Privacy",
            body: `MatchInsense collects no personal data from anyone, including children. The platform is safe to browse for all ages.

However, AI-generated betting insights displayed on the platform are intended for users aged 18 and over only.`
          },
          {
            title: "8. Your Rights",
            body: `Since we collect no personal data, there is nothing for us to provide, correct or delete on your behalf. Your AI reports exist only on your device and are entirely within your control.

If you believe we have inadvertently received personal data about you, contact privacy@matchinsense.com and we will respond within 30 days.`
          },
          {
            title: "9. Changes to This Notice",
            body: `We may update this Privacy Notice to reflect changes in our practices or applicable law. The date of the most recent update appears at the top of this page. Continued use of MatchInsense after an update constitutes acceptance of the revised notice.`
          },
        ].map(s => (
          <div key={s.title}>
            <h2 style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", margin: "0 0 10px", borderBottom: "1px solid var(--border)", paddingBottom: 8 }}>{s.title}</h2>
            <p style={{ fontSize: 13, lineHeight: 1.85, color: "var(--text-2)", margin: 0, whiteSpace: "pre-line" }}>{s.body}</p>
          </div>
        ))}

        <div style={{ borderTop: "1px solid var(--border)", paddingTop: 20 }}>
          <p style={{ fontSize: 12, color: "var(--text-3)", lineHeight: 1.65, margin: 0 }}>
            Questions? <a href="mailto:privacy@matchinsense.com" style={{ color: "var(--accent)" }}>privacy@matchinsense.com</a>
          </p>
        </div>
      </div>
    </div>
  );
}